# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
cbor_metadata = false
evm_version = "paris"
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "artifacts-foundry"
script = "scripts/foundry"
solc = "0.8.20"
src = "contracts"
test = "test/foundry"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]





[profile.default.fuzz]
max_test_rejects = 1_000_000
runs = 1_000

[profile.default.invariant]
call_override = false
depth = 15
fail_on_revert = true
runs = 256

[profile.lite]
optimizer = false

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[doc]
ignore = ["**/*.t.sol"]
out = "docs"


[etherscan]
goerli = { key = "${ETHERSCAN_API}" }
mainnet = { key = "${ETHERSCAN_API}" }
sepolia = { key = "${ETHERSCAN_API}" }
bsc = { key = "${ETHERSCAN_BSC_API}" }
polygon = { key = "${ETHERSCAN_POLYGON_API}" }
polygonzk = { key = "${ETHERSCAN_POLYGON_ZK_API}" }
mumbai = { key = "${ETHERSCAN_POLYGON_API}" }
optimism = { key = "${ETHERSCAN_OPTIMISM_API}" }
ogoerli = { key = "${ETHERSCAN_OPTIMISM_API}" }
arbitrum = { key = "${ETHERSCAN_ARBITRUM_API}" }
arbgoerli = { key = "${ETHERSCAN_ARBITRUM_API}" }
base = { key = "${ETHERSCAN_BASE_API}" }
avalanche = { key = "${ETHERSCAN_AVALANCHE_API}" }
fantom = { key = "${ETHERSCAN_FANTOM_API}" }
gnosis = { key = "${ETHERSCAN_GNOSIS_API}" }
linea = { key = "${ETHERSCAN_LINEA_API}" }

[fmt]
# Optional formatting preferences

[rpc_endpoints]
localhost = "http://localhost:8545"
goerli = "https://eth-goerli.alchemyapi.io/v2/${ALCHEMY_ID}"
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_ID}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_ID}"
bsc = "https://bsc-dataseed.binance.org"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_ID}"
polygonzk = "https://zkevm-rpc.com"
mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_ID}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_ID}"
ogoerli = "https://opt-goerli.g.alchemy.com/v2/${ALCHEMY_ID}"
osepolia = "https://sepolia.optimism.io"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_ID}"
arbgoerli = "https://goerli-rollup.arbitrum.io/rpc"
arbsepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base = "https://mainnet.base.org"
baseGoerli = "https://goerli.base.org"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
fantom = "https://rpcapi.fantom.network/"
gnosis = "https://rpc.gnosischain.com"
linea = "https://linea-mainnet.infura.io/v3/${INFURA_ID}"
zksync = "https://mainnet.era.zksync.io"
zkatana = "https://rpc.zkatana.gelato.digital"
unreal = "https://rpc.unreal.gelato.digital"
geloptestnet = "https://rpc.op-testnet.gelato.digital"
